version: "3.6"
services:
  client:
    build: 
        context: ./client
    environment: 
        - NODE_ENV=development   
    expose: 
        - ${REACT_APP_PORT}
    ports:
        - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes: 
        - ./client/src:/src
        - ./client/node_modules:/node_modules
    links:
        - server
    command: npm run start
  server:
    build: ./server
    expose: 
        - ${APP_SERVER_PORT}
    environment: 
        API_HOST: ${API_HOST}
        APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
        - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes: 
        - ./server/src:/src/
    command: npm run start