export const ADD_TO_CART_ITEM = "ADD_TO_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SHIPPING_CART_SAVE = "SHIPPING_CART_SAVE";
export const PAYMENT_CART_SAVE = "PAYMENT_CART_SAVE";