// IS ADMIN
export const IS_ADMIN_REQUEST = "IS_ADMIN_REQUEST"
export const IS_ADMIN_SUCCESS = "IS_ADMIN_SUCCESS"

export const ADMIN_REMOVE = "ADMIN_REMOVE"

export const IS_ADMIN_FAIL = "IS_ADMIN_FAIL"
